Fix CI Pipeline to Wait for Container Readiness before Version Check (#31)
* first commit

* updating CI

* testing CI

* updating CI

* updating CI

* updating CI

---------

Co-authored-by: keji-dev <keji-dev@DESKTOP-F7J4C1C>

diff --git a/.github/workflows/hivebox-test.yml b/.github/workflows/hivebox-test.yml
--- a/.github/workflows/hivebox-test.yml
+++ b/.github/workflows/hivebox-test.yml
@@ -5,8 +5,14 @@ on:
         - 'release/*'
         - 'testing/*'
         - 'feature/*'
-        - 'dev/'
+        - 'dev'
         - main
+      paths-ignore:
+        - README.md
+
+    pull_request:
+      branches:
+        - 'main'
       paths-ignore:
         - README.md
 
@@ -75,5 +81,20 @@ jobs:
         - name: Test /version endpoint
           run: |
             docker run -d -p 8080:8080 hivebox:latest
-            sleep 5
-            curl http://localhost:8080/version
+
+            TIMEOUT=300
+            TIME_ELAPSED=0
+
+            until curl -s http://localhost:8080/version; do
+              if [ $TIME_ELAPSED -ge $TIMEOUT ]; then
+                echo "[ERROR] Timeout reached after $TIMEOUT seconds, stopping the pipeline..."
+                exit 1
+              fi
+
+              echo "[INFO] Waiting for hivebox container..."
+              sleep 5
+              TIME_ELAPSED=$((TIME_ELAPSED + 5))
+
+            done
+
+            echo "[OK] /version test has been completed successfully"
